### ISSUE TITLE
roxygenize not creating usable .Rd files

### ISSUE THREAD

**Issue by ngotelli** [GotelliLab/EcoSimR#21]
Hi Ted:

I went in to finish the documentation of existing functions in the library and ran into a problem. Briefly, I cloned the repository and initially found all the `.Rd` files that should be there in the `man` folder and everything else in order. Next, I ran through the following code that you sent me:

```{r}
library(devtools)
library(roxygen2)

path <-  getwd()
dev_mode()
roxygenize(path)
install(path)
library(EcoSimR)
```

When the path was roxygenized, I noticed it was also deleting some files, and those were ones that used to be named in caps (`RA1`-`RA4`, `Pianka`, `Czechanowski`, `Sim1`-`Sim8`,`Sim10`). After that first pass through with roxygenize, those `.Rd` files are now missing, even though the functions are still present in the `algorithms` and `metrics`  source files.

Next, I re-roxygenized the path and the renamed functions were restored with their `.Rd` files written. All good, and I never generated any errors or warnings with the R commands. But when I go to load anything in the EcoSimR help system from the library, I get the following sort of error:

> error in fetch(key): cannot allocate memory block of size 2.2 GB

Possibly I screwed something up 5 months ago when I pushed my changes, but everything was working correctly in my cloned version then.

Thanks for your help. I would really like to get this documentation completed so we can move on to the next phase!

Best,

Nick

**Comment by emhart** [comment]
Hi Nick,

I checked this.  The reason that all the files were deleted is that we probably haven't run the documentation in awhile.  I know at some point I renamed all the functions to be lowercase, e.g. "RA1" became "ra1", so that's why you see files being deleted.  

As far as the memory error, I think that's just a coincidence.  You can read more about it here: http://stackoverflow.com/questions/10373098/error-in-fetchkey-internal-error-3-in-r-decompress1
 and here:
http://r.789695.n4.nabble.com/R-Memory-Issues-td4630667.html

I've pushed the latest version.  It should have all your changes.  Try just installing the latest version with this code. 

```R
library(devtools)
install_github("GotelliLab/EcoSimR")
library(EcoSimR)
help(ra1)
help(sim4)
```

If you have problems after you install from github with accessing the help files, just reboot R, and don't install again, just load the library and test the help files.  I'm not sure why the `fetch` error comes after installing, but the reboot fixes it.

**Comment by ngotelli** [comment]
Hi Ted:
That did the trick. I have to reboot to avoid the memory error, but then I can see my changes. Thanks!

Nick
