### ISSUE TITLE
Documentation style look OK?

### ISSUE THREAD

**Issue by ngotelli** [GotelliLab/EcoSimR#22]
Hi Ted:

OK, I have pushed some documentation for the `pianka` niche overlap index. Please take a look and see if this is OK. I have tried to imitate the style in other R packages. The material found said I could use LaTeX in the documentation, but when I tried I could only generate very simple equations with no superscripts, subscripts, or summation. That's a shame, but it seems to be that way for other packages as well.

If this looks OK to you, I will move on to the rest of the documentation. It sure is a nuisance to have to quit R every time I want to inspect the help system, but at least now I have a working template.

Best,

Nick

**Comment by emhart** [comment]
@ngotelli Hi Nick,

What you probably want to use is `\deqn{latex}{ascii}`.  The first set of brackets holds a latex equation that gets rendered when the full PDF documentation is created, and the ascii part goes in the actual HTML docs that you see when you use `help()`.  It will try and convert latex to ascii if you only give it latex, but it doesn't look great for complex equations.  [Check out the example I did for Pianka](https://github.com/GotelliLab/EcoSimR/blob/1a66ba8666785b2236e53f7ce36ec1dd0f678646/R/metrics.R#L21-L23)  

Otherwise the documentation looks great!  If anything I'd say that including the actual equations is overkill.  I would think you could just write "See eqn 5 in Pianka 1973", but if you think it's better with the equations then we can include them.
