### ISSUE TITLE
Correct branch for last push/pull?

### ISSUE THREAD

**Issue by ngotelli** [GotelliLab/EcoSimR#33]
Hi Ted:

I just completed some annotations for the size overlap metrics. But when I went to push them, it failed because the branch was not up to date. So, I pulled changes first, and then the push worked fine. My concern now is that I appeared to have pulled and then pushed to the master branch. But now I wonder if I shouldn't have been on the dev branch? Sorry if I have botched this up, but hopefully you can repair it quickly if I have made a mistake. I am still wearing my "newbie hat" on GitHub.

Best,

Nick

**Comment by emhart** [comment]
Hi Nick,

You didn't botch anything as far as I can tell.  All I noticed was that were a bunch of temporary vim files, and somehow you created an empty folder.  At the moment because there's no release, committing to master is fine.  In the future once it's released it's probably better to work off a dev branch.
