### ISSUE TITLE
build homepage for ecosimr.org

### ISSUE THREAD

**Issue by emhart** [GotelliLab/EcoSimR#58]
I think what might work best would be to build a simple home page for ecosimr.org.  It can hold a brief introduction to the package via a quick start guide and some links to relevant literature.  Then we can maintain a separate domain for the docs, like docs.ecosimr.org.  Does this sound like overkill?  I'm essentially imagining a structure like ggplot2.org and docs.ggplot2.org.

**Comment by emhart** [comment]
@ngotelli What do you think of this strategy?  I'm not sure we actually would have that much to put on a homepage at the moment.  We could just put docs.ecosimr.org as ecosimr.org.

**Comment by ngotelli** [comment]
Hi @emhart  . Sorry to be out of touch. I would like a homepage posting for my personal website because so many people come to it. I really like the static docs look, so is there a way I can build a page with that? It would be good if it could show your quickstart, just to tempt non-R users to take the plunge. I'd also like to be able to distribute the zipped file of the "old" EcoSim, just to preserve the legacy version.

I will try to finish off the documentation by the end of this week.

**Comment by emhart** [comment]
Hi @ngotelli 

I'll whip something up with rmarkdown because it seems that it would be just one page.  I'll use the CSS and start a new repo.  As far as where to host the webpage, you can host a version there, or just redirect to ecosimr.org from whatever page you want.  Whichever you prefer.  Finally, I think that we should host a binary of the old ecosim on either zenodo.org or figshare.org and give it a DOI so it's citable.

**Comment by emhart** [comment]
Here's a quick work up @ngotelli you can see it here http://ecosimr.org .  The page is built using markdown so you can easily build the main content.   Just make changes here and then build to html.  https://github.com/GotelliLab/ecosimrWeb

**Comment by emhart** [comment]
Web page is up at ecosimr.org
