### ISSUE TITLE
Delete and retag release, get new DOI

### ISSUE THREAD

**Issue by emhart** [GotelliLab/EcoSimR#69]
I tagged the release too early, getting the package up on CRAN took a bit more work than I expected.  I also should upload a new version to ZENODO or FigShare

**Comment by ngotelli** [comment]
Hi @emhart Do you know if CRAN is going to post a binary so that EcoSimR shows up in the list of packages available in R (or RStudio)?  For now, you can't find it if you go looking at the package list from R or RStudio. However, knowing it exists, I can install it from the R console with

install.packages("EcoSimR", type="source")

Best,

Nick

**Comment by emhart** [comment]
It usually takes a couple of days, and then it should show up...

**Comment by emhart** [comment]
In fact you can see it's up now.  http://cran.r-project.org/web/packages/EcoSimR/

**Comment by ngotelli** [comment]
Awesome! :+1:

**Comment by emhart** [comment]
DOI's are fully updated.
